### ISSUE TITLE
binary file

### ISSUE THREAD

**Issue by hiscal2015** [AccelerationNet/access2csv#11]
./access2csv myfile.accdb

seems above command uses a binary file access2csv instead of using jar file, when can I find it?

**Comment by bobbysmith007** [comment]
I am not sure (I inherited this project) but my guess would be that it is a bash script that invokes java/the jar with the correct parameters

**Comment by bobbysmith007** [comment]
https://github.com/AccelerationNet/access2csv/blob/master/access2csv
