### ISSUE TITLE
jar with password flag

### ISSUE THREAD

**Issue by hiscal2015** [AccelerationNet/access2csv#12]
Hi, May I have the latest release with --password flag?

Seems build from source code with the latest master branch, there wasn't an valid access2csv.jar file there... Thanks for the help.

root@ubuntu16:~/access2csv/target# ll
total 1788
drwxr-xr-x 11 root root    4096 Apr  9 18:51 ./
drwxr-xr-x  6 root root    4096 Apr  9 18:52 ../
-rw-r--r--  1 root root    8667 Apr  9 18:51 access2csv-0.2-SNAPSHOT-bin.tar.bz2
-rw-r--r--  1 root root    8166 Apr  9 18:51 access2csv-0.2-SNAPSHOT-bin.tar.gz
-rw-r--r--  1 root root    8345 Apr  9 18:51 access2csv-0.2-SNAPSHOT-bin.zip
-rw-r--r--  1 root root    7417 Apr  9 18:50 access2csv-0.2-SNAPSHOT.jar
-rw-r--r--  1 root root 1720717 Apr  9 18:51 access2csv-0.2-SNAPSHOT-jar-with-dependencies.jar
-rw-r--r--  1 root root    4815 Apr  9 18:51 access2csv-0.2-SNAPSHOT-tests.jar
drwxr-xr-x  4 root root    4096 Apr  9 18:50 appassembler/
drwxr-xr-x  2 root root    4096 Apr  9 18:51 archive-tmp/
drwxr-xr-x  3 root root    4096 Apr  9 18:50 classes/
drwxr-xr-x  3 root root    4096 Apr  9 18:50 generated-sources/
drwxr-xr-x  3 root root    4096 Apr  9 18:50 generated-test-sources/
-rw-r--r--  1 root root    9998 Apr  9 18:50 jacoco.exec
drwxr-xr-x  2 root root    4096 Apr  9 18:50 maven-archiver/
drwxr-xr-x  3 root root    4096 Apr  9 18:50 maven-status/
drwxr-xr-x  2 root root    4096 Apr  9 18:50 surefire-reports/
drwxr-xr-x  3 root root    4096 Apr  9 18:50 test-classes/

root@ubuntu16:~/access2csv/target# java -jar access2csv-0.2-SNAPSHOT-jar-with-dependencies.jar --help
no main manifest attribute, in access2csv-0.2-SNAPSHOT-jar-with-dependencies.jar

**Comment by peterhatz** [comment]
Hi,

I've compiled from the latest source and run **appassembler/bin/access2csv**, I don't get the password option?

Not sure if I'm doing something wrong...?

Thanks,
Peter
