### ISSUE TITLE
Does not capture header/title/first row

### ISSUE THREAD

**Issue by gamesguru** [AccelerationNet/access2csv#15]
it's making it rather difficult to sort through some of this data.  Am I missing a simple command to capture this?  Thanks

here's one of the offending .accdb files for you to reproduce the issue
[PA02.zip](https://github.com/AccelerationNet/access2csv/files/1588282/PA02.zip)

**Comment by ayee-hatfield** [comment]
what is the command you use (including the options)?

**Comment by ayee-hatfield** [comment]
@--with-header@ to include header row. It does not take any true/false parameter.

**Comment by ayee-hatfield** [comment]
oops.
--with-header

**Comment by gamesguru** [comment]
i read somewhere else there is a --schema command which lists them out.  That works, assuming you don't have too many to copy by hand.  Thanks for that though

**Comment by bobbysmith007** [comment]
So can this be closed?
